name: Hello World Workflow

on:
  repository_dispatch:
    types: [ntfy-trigger]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Run hello world script
      run: |
        python hello_world.py
      env:
        # You can access custom data sent in the webhook
        MESSAGE: ${{ github.event.client_payload.message }}
