name: Run Hello World Script

on:
  workflow_dispatch:  # Allows manual triggering from the GitHub Actions UI
  push:
    branches:
      - main  # Optional: Trigger on push to main branch

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the Python version

      - name: Install dependencies (if any)
        run: echo "No dependencies required for this example."

      - name: Run Hello World Script
        run: python hello_world.py
