name: Run Hello World on ntfy Message
on:
  repository_dispatch:
    types: [ntfy_message_received]
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run Hello World script
        run: python3 hello_world.py
